//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metro_Time
    {
        public int ID { get; set; }
        public int Hours { get; set; }
        public int Minuts { get; set; }
    
        public virtual Metro_Branch Metro_Branch { get; set; }
    }
}
