//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursWorkEntities : DbContext
    {
        public KursWorkEntities()
            : base("name=KursWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Metro> Metro { get; set; }//
        public virtual DbSet<Metro_Branch> Metro_Branch { get; set; }//
        public virtual DbSet<Route> Route { get; set; }//
        public virtual DbSet<Stop> Stop { get; set; }//
        public virtual DbSet<Users> Users { get; set; }//
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Metro_Time> Metro_Time { get; set; }//
        public virtual DbSet<Time> Time { get; set; }//
    }
}
