//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserFavourite { get; set; }//string
        public string UserEmail { get; set; }
    
        public virtual Route Route { get; set; }

        public override string ToString()
        {
            return this.UserEmail + "   " + this.UserLogin + "   " + this.UserPassword;
        }
    }
}
